export const indexableRoutes = [
  { path: '/', priority: 1, changeFrequency: 'weekly' },
  { path: '/servicos', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/eventos-corporativos-rio-de-janeiro', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/eventos-privados-rio-de-janeiro', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/experiencias-de-marca', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/concierge-rio-de-janeiro', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/experiencias', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/sobre', priority: 0.6, changeFrequency: 'yearly' },
  { path: '/contato', priority: 0.8, changeFrequency: 'yearly' },
  { path: '/faq', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/por-que-riosilux', priority: 0.6, changeFrequency: 'yearly' },
  { path: '/casamentos-luxo-ipanema', priority: 0.55, changeFrequency: 'monthly' },
  { path: '/despedida-solteiro-luxo-rj', priority: 0.45, changeFrequency: 'monthly' },
  { path: '/eventos-barra-tijuca', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/eventos-mansoes-rio', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/experiencias-exclusivas-rio', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/producao-eventos-leblon', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/blog', priority: 0.55, changeFrequency: 'weekly' },
  { path: '/blog/concierge-vs-agencia-eventos', priority: 0.45, changeFrequency: 'yearly' },
  { path: '/blog/guia-despedida-solteiro-luxo', priority: 0.4, changeFrequency: 'yearly' },
  { path: '/blog/melhores-locais-eventos-rio', priority: 0.45, changeFrequency: 'yearly' },
  { path: '/blog/roi-eventos-corporativos', priority: 0.45, changeFrequency: 'yearly' },
  { path: '/blog/tecnologia-eventos-premium', priority: 0.4, changeFrequency: 'yearly' },
  { path: '/blog/tendencias-eventos-premium-2025', priority: 0.35, changeFrequency: 'yearly' },
] as const
